[project]
name = "erav4-s3"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flask>=3.1.2",
    "google>=3.0.0",
    "google-genai>=1.33.0",
    "google-generativeai>=0.8.5",
    "nsepython>=2.97",
]
